uncommented the line

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,8 +1,8 @@
 name: CI/CD
 
-#on: push
+on: push
 
-#jobs:
+jobs:
   build: 
     runs-on: ubuntu-latest
 
@@ -12,8 +12,8 @@ name: CI/CD
       - name: Run a one-line script
         run: echo "Hello, CI/CD!"
 
-      #- name: Simulate an error
-      #  run: echo "About to fail" ; exit 1
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
 
       - name: Another greeting
         run: echo "Hello, CI/CD again!"
